source 'http://git.oschina.net/akuandev/Specs.git'
platform :ios, '7.0'

pod 'AFNetworking', '~> 2.5.4'
pod 'SDWebImage', '~> 3.7.2'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'BlocksKit', '~> 2.2.5'
pod 'Masonry', '~> 0.6.1'
pod 'RDVTabBarController', '~> 1.1.9'
pod 'TTTAttributedLabel', '~> 1.13.4'
pod 'ODRefreshControl', '~> 1.1.0'
pod 'MJRefresh', '~> 1.4.7'
pod 'Qiniu', '~> 7.0.9.1'
pod 'YTKKeyValueStore', '~> 0.1.2'
pod 'SpinKit', '~> 1.2.0'
pod 'JHChainableAnimations'